---
title: "R Notebook"
output: html_notebook
---

```{r}
require(ggplot2)
require(bbplot)
require(lubridate)
require(dplyr)
```

```{r}
setwd("~/Development/f1-google-trends/hungary")
df <- read.csv("~/Development/f1-google-trends/hungary/data/df.csv")
```

```{r}
colnames(df) <- c("Time", "interest")
```


```{r}
# First, convert your string to POSIXct with "America/Chicago" timezone
df$tzts <- as.POSIXct(df$Time, tz = "America/New_York", format = "%Y-%m-%dT%H:%M:%S")

# Then convert it to UTC
attributes(df$tzts)$tzone <- "UTC"
```

```{r}
df$is_max <- df$interest == max(df$interest, na.rm = TRUE)
```


```{r}
p <- ggplot(df, aes(x = tzts, y = interest)) +
  geom_line() +
  geom_point(aes(size = is_max)) +  # adjust size based on is_max
  scale_size_manual(values = c(1, 4)) +  # adjust point sizes (small and large)
  ylim(0, 100) +
  labs(title="Google Trends' Interest over time of the phrase \"formula 1\"",
       subtitle = "Queried on Sunday, July 23, 2023 at 15:04 UTC") +
  xlab('Time') + ylab('Interest') +
  bbc_style() +
  scale_x_datetime(expand=c(0,0),
                     date_breaks= "10 mins", date_labels = "%H:%M") +
  theme(axis.title = element_text(size = 20), 
        plot.margin = unit(c(1.0,1.5,1.0,1.0), 'cm'),
        axis.title.y = element_text(margin = margin(t = 0, r = 20, b = 0, l = 0)),
        legend.position = 'none',
        axis.text.x = element_text(angle = 0, hjust = 1)) 
print(p)
```

```{r}
ggsave(sprintf('plots/%s.jpg', '1'), plot = p, 
           width = 16, height = 8, units = 'in')
```

